name: blank
description: a blank issue. DO NOT USE THIS AS THIS IS THE BASE TEMPLATE FOR OTHER TEMPLATES
labels: [tpl]
title: "[tpl]"

body:
  - type: markdown
    attributes:
      value: |
        # READ THIS BEFORE OPENING AN ISSUE

        This form is A BASE TEMPLATE. YOUR ISSUE WILL BE CLOSED IF YOU IGNORE THIS.
        
        DO NOT USE THIS FORM.

    - type: checkboxes
      id: agreements-lmao
      attributes:
        label: Agreements, please check both before continuing
        options:
          - label: I agree that my issue may go unanswered
            required: true
          - label: I agree that what is contained in the error log i have uploaded may contain information relating to my PC
            required: true
