name: Crashing Error
description: For reporting an error that causes a crash
labels: [Crashing Error]
title: "[Crashing Error]"
body:
  - type: markdown
    attributes:
      value: |
        # Reporting a Crashing Error
        Hello! Thank you for taking the time to report an error that has caused a crash. Your feedback is valuable to us, and we are here to assist you in resolving this issue.
        
        ## Information Required for Reporting
        Please ensure you have the following information ready to upload:
        1. **Crash Log:** You can find the crash logs in the `.minecraft/crash-reports/` directory.
        2. **List of Mods:** Generate a list of your installed mods by running the `tree` command or a similar command.
        3. **LUA Files:** Provide the list and contents of any LUA files involved.
        
        ## Upload Guidelines
        To help us assist you better, please follow these upload guidelines:
        - **Preferred Method:** Bundle all the required files together in a single .zip file.
        - **Alternative Methods:** If zipping is not possible, you may upload the files separately (e.g., .txt, .png, etc.). For LUA files, it is mandatory to zip them up before uploading.
        
        For instructions on how to zip files, please refer to this [guide](https://support.microsoft.com/en-gb/windows/zip-and-unzip-files-8d28fa72-f2f9-712f-67df-f80cf89fd4e5).
        
        We apologize for any inconvenience caused by this issue and appreciate your patience and cooperation.

  - type: textarea
    id: upload-area
    attributes:
      label: Upload Area
      description: Please upload your files here.
      placeholder: Drag and drop or select your crash log, mods list, and LUA files to upload.
    validations:
      required: true

  - type: checkboxes
    id: agreements
    attributes:
      label: Agreement and Confirmation
      options:
        - label: I confirm that I have uploaded all required data as outlined in the 'Information Required for Reporting' section. Failure to do so may result in delayed support for this error.
          required: true
        - label: I acknowledge that the uploaded information may contain identifiable details related to my computer system.
          required: true
        - label: I have attempted basic troubleshooting steps, such as disabling mods, ensuring all required mods are installed, and performing a clean boot of my computer.
          required: true
