name: Feature Suggestion
description: Use this template to suggest new features for Neo Client
labels: [Feature Request]
title: "[Feature Request] <Your Feature Title Here>"
body:
  - type: markdown
    attributes:
      value: |
        # Suggest a New Feature
        
        Hello! Thank you for taking the time to suggest a new feature for Neo Client.
        
        We truly value your input and aim to review all suggestions promptly. However, if you don't hear back from us within a month, please be patient as we might be busy with other tasks. Rest assured, we will get back to you as soon as possible!
        
        ## Information Required
        To help us understand your suggestion better, please provide the following information:
        1) A **detailed** description of the feature you are suggesting.
        2) Indicate if the feature is related to an existing bug.
        3) Specify the scope of the feature (either Lua or Java).
        
        Thank you for providing all necessary details and helping us improve Neo Client!

  - type: textarea
    id: description
    attributes:
      label: Detailed Feature Description
      description: Provide a comprehensive and detailed description of the feature you are suggesting.
    validations:
      required: true

  - type: dropdown
    id: scope
    attributes:
      label: Feature Scope
      description: Select the relevant scope for your feature suggestion.
      options:
        - Lua
        - Java
    validations:
      required: true

  - type: checkboxes
    id: bug_related
    attributes:
      label: Is this feature related to a bug?
      description: Select whether your feature suggestion is related to an existing bug.
      options:
        - label: Yes, it is bug-related
          required: false
        - label: No, it is not bug-related
          required: false

  - type: input
    id: bug_url
    attributes:
      label: Bug Report URL
      description: If your feature is related to a bug, please enter the URL to the bug report here.
    validations:
      required: false
